import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import ObserverProvider from "@/utils/ObserverProvider";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });
//
// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Johnk",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="scroll-smooth overscroll-y-none" lang="en">
      <body
        className={`antialiased bg-black`}
      >
          {children}
      </body>
    </html>
  );
}

// background: linear-gradient(180deg, #807401 0%, #9C6E0B 0.01%, #DBC60A 15.38%, #88750C 100%);